# {{.ProjectName}}

This project was generated by [GoForge](https://github.com/night-slayer18/goforge).

## 🚀 Getting Started

This project is structured using a clean architecture pattern to ensure separation of concerns and scalability.

### Prerequisites

- Go (version {{.GoVersion}} or newer)
- The `goforge` CLI tool

### Running the Application

1.  **Run the development server:**
    ```bash
    goforge run dev
    ```
    The server will start on the port defined in `config/default.yml`.

2.  **Build for production:**
    ```bash
    goforge build
    ```
    This will create a production-ready executable in the `/dist` directory.

### Available Scripts

This project uses `goforge` to manage scripts, similar to `npm` scripts.

-   `goforge run dev`: Starts the application in development mode with hot-reloading.
-   `goforge run build`: Builds the application for production.
-   `goforge run test`: Runs all tests in the project.

You can find and add more scripts in the `goforge.yml` file.
